#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use App\Application\Console\Command\GameCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new GameCommand());
$application->setDefaultCommand('game', true);
$application->run();